<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
/**
 * This is the model class for table "categorias".
 *
 * @property integer $idcategoria
 * @property string $descripcion
 * @property integer $create_by
 * @property integer $update_by
 * @property string $sincronizaciones
 *
 * @property Productos[] $productos
 * @property Productos[] $ultproductos
 */

class Categorias extends \yii\db\ActiveRecord {
	/**
	 * @inheritdoc
	 */
	public static function tableName() {
		return 'categorias';
	}

	public function behaviors() {
		return [
			'blameable'           => [
				'class'              => BlameableBehavior::className(),
				'createdByAttribute' => 'create_by',
				'updatedByAttribute' => 'update_by'
			]
		];
	}

	public function beforeSave($insert)
    {
        $this->descripcion=mb_strtoupper($this->descripcion,'utf-8');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
	 * @inheritdoc
	 */
	public function rules() {
		return [
			[['descripcion'], 'required'],
			[['create_by', 'update_by'], 'integer'],
			[['sincronizaciones'], 'string'],
			[['descripcion'], 'string', 'max' => 145],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels() {
		return [
			'idcategoria' => 'ID',
			'descripcion' => 'DESCRIPCION',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getProductos() {
		return $this->hasMany(Productos::className(), ['idcategoria' => 'idcategoria']);
	}

	public function getUltproductos() {
		return $this->hasMany(Productos::className(), ['idcategoria' => 'idcategoria'])
			->orderBy(['idproducto'                                     => SORT_DESC])->limit(10);
	}
}
