<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
/**
 * This is the model class for table "laboratorio".
 *
 * @property integer $idlaboratorio
 * @property string $nombre
 * @property integer $create_by
 * @property integer $update_by
 * @property string $sincronizaciones
 *
 * @property Labproveedor[] $labproveedores
 * @property Productos[] $productos
 */
class Laboratorio extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'laboratorio';
    }
    
    public function behaviors() {
        return [
            'blameable' => [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'create_by',
                'updatedByAttribute' => 'update_by'
            ]
        ];
    }

    public function beforeSave($insert)
    {
        $this->nombre=mb_strtoupper($this->nombre,'utf-8');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['create_by', 'update_by'], 'integer'],
            [['sincronizaciones'], 'string'],
            [['nombre'], 'string', 'max' => 45],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'idlaboratorio' => 'ID',
            'nombre' => 'NOMBRE',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLabproveedores()
    {
        return $this->hasMany(Labproveedor::className(), ['idlaboratorio' => 'idlaboratorio']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductos()
    {
        return $this->hasMany(Productos::className(), ['idlaboratorio' => 'idlaboratorio'])->orderBy('descripcion');
    }
}
